/* eslint-disable no-undef */
// @ts-nocheck
import { useEffect, useState } from 'react'
import { PropertyGallery } from './PropertyGallery'
import { PropertyMap } from './PropertyMap'
import { PropertyComparison } from './PropertyComparison'
import { ActivityTimeline } from './ActivityTimeline'
import { InvestmentMemo } from './InvestmentMemo'
import { ExportMenu } from './ExportMenu'


export function TabContent({ tab, property, properties, memo, notes, tasks, documents, refresh }: { tab: Tab; property: Property; properties: Property[]; memo: Memo | null; notes: Note[]; tasks: Task[]; documents: Document[]; refresh: () => Promise<void> }) {
  const output = property.underwriting_output
  if (tab === 'Overview') return <Overview property={property} memo={memo} tasks={tasks} refresh={refresh} />
  if (tab === 'Listing') return <DataSection title="Listing details" data={{ address: property.address, county: property.county, asking_price: property.asking_price, description: property.description }} />
  if (tab === 'Activity Timeline') return <ActivityTimeline property={property} notes={notes} documents={documents} />
  if (tab === 'Financials') return <DataSection title="Workbook financial summary" data={output?.dashboard ?? {}} />
  if (tab === 'Underwriting') return <div className="two-column"><DataSection title="Assumptions used" data={output?.assumptions ?? {}} /><DataSection title="Traceability" data={output?.traceability ?? {}} /></div>
  if (tab === 'Renovation') return <DataSection title="Renovation range and categories" data={output?.renovation ?? {}} />
  if (tab === 'Airbnb') return <Suitability title="Airbnb suitability" score={property.airbnb_score} field={property.enrichment_data.airbnb_suitability} />
  if (tab === 'Wedding') return <Suitability title="Wedding suitability" score={property.wedding_score} field={property.enrichment_data.wedding_suitability} />
  if (tab === 'Maps') return <><PropertyMap property={property} /><EnrichmentGrid property={property} /></>
  if (tab === 'Comparable Sales') return properties.length > 1 ? <PropertyComparison properties={properties} /> : <Comparables memo={memo} />
  if (tab === 'Documents') return <Documents propertyId={property.id} documents={documents} refresh={refresh} />
  return <NotesAndTasks propertyId={property.id} notes={notes} tasks={tasks} refresh={refresh} />
}

export function Dashboard({ properties }: { properties: Property[] }) { const average = (values: Array<number | null>) => { const valid = values.filter((value): value is number => value != null); return valid.length ? valid.reduce((a, b) => a + b, 0) / valid.length : null }; const highest = [...properties].sort((a, b) => (b.overall_score ?? 0) - (a.overall_score ?? 0))[0]; return <section className="dashboard-grid"><Metric label="Properties imported" value={String(properties.length)} /><Metric label="Deals under review" value={String(properties.filter((property) => ['Reviewing', 'Underwriting'].includes(property.status)).length)} /><Metric label="Average Buy Score" value={score(average(properties.map((property) => property.buy_score)))} /><Metric label="Average IRR" value={percent(average(properties.map((property) => property.underwriting_output?.projection.levered_irr ?? null)))} /><Metric label="Highest-scoring property" value={highest ? `${highest.name} · ${Math.round(highest.overall_score ?? 0)}` : '—'} /><Metric label="Pipeline counts" value={`${properties.filter((property) => property.status === 'Closed').length} closed`} /></section> }
function Metric({ label, value }: { label: string; value: string }) { return <article><span>{label}</span><strong>{value}</strong></article> }
function Overview({ property, memo, tasks, refresh }: { property: Property; memo: Memo | null; tasks: Task[]; refresh: () => Promise<void> }) {
  return <div className="overview-grid"><PropertyGallery images={property.images} /><InvestmentMemo memo={memo} confidence={property.confidence_score} /><ExportMenu propertyId={property.id} /><article className="panel"><div className="panel-title"><span>Property facts</span></div><dl className="facts"><Fact label="Asking price" value={money(property.asking_price)} /><Fact label="Annual taxes" value={money(property.annual_taxes)} /><Fact label="Beds / baths" value={`${property.bedrooms ?? '—'} / ${property.bathrooms ?? '—'}`} /><Fact label="Square feet" value={property.square_feet?.toLocaleString() ?? '—'} /><Fact label="Acreage" value={property.acreage?.toString() ?? '—'} /><Fact label="County" value={property.county ?? '—'} /></dl></article><article className="panel task-panel"><div className="panel-title"><span>Open tasks</span><span>{tasks.filter((task) => !task.completed).length}</span></div>{tasks.slice(0, 4).map((task) => <TaskRow key={task.id} propertyId={property.id} task={task} refresh={refresh} />)}{!tasks.length && <p className="muted">No tasks yet. Add one in Notes.</p>}</article><article className="panel missing-panel"><div className="panel-title"><span>Missing information</span><span>{memo?.missing_information.length ?? 0}</span></div><div className="chip-list">{memo?.missing_information.map((item) => <span key={item}>{labelize(item)}</span>)}</div></article></div>
}

function EnrichmentGrid({ property }: { property: Property }) { return <div className="enrichment-grid">{Object.entries(property.enrichment_data).map(([key, field]) => <article className="panel" key={key}><div className="panel-title"><span>{labelize(key)}</span><span>{Math.round(field.confidence * 100)}%</span></div><strong className="enrichment-value">{field.value === null ? 'Needs verification' : String(field.value)}</strong><small>{field.source}</small><small>Updated {new Date(field.last_updated).toLocaleDateString()}{Date.now() - new Date(field.last_updated).getTime() > 30 * 86400000 ? ' · Stale' : ''}</small>{field.missing_reason && <small>{field.missing_reason}</small>}</article>)}</div> }
function Suitability({ title, score: value, field }: { title: string; score: number | null; field?: EnrichmentField }) { return <article className="panel suitability"><div className="score-ring">{Math.round(value ?? 0)}</div><div><div className="eyebrow">Bistate suitability model</div><h2>{title}</h2><p>{field?.value === null || !field ? 'Provider facts are incomplete. Verify local regulations, demand, and physical feasibility before approval.' : 'The initial suitability score uses available property facts. Validate it with market and regulatory diligence.'}</p><small>Source: {field?.source ?? 'Not available'} · Confidence {Math.round((field?.confidence ?? 0) * 100)}%</small></div></article> }
function DataSection({ title, data }: { title: string; data: Record<string, unknown> }) { return <article className="panel data-panel"><div className="panel-title"><span>{title}</span></div><div className="data-grid">{Object.entries(data).map(([key, value]) => <div key={key}><span>{labelize(key)}</span><strong>{formatValue(value)}</strong></div>)}</div></article> }
function Comparables({ memo }: { memo: Memo | null }) { return <article className="panel"><div className="panel-title"><span>Verified comparable sales</span><span>{memo?.comparable_properties.length ?? 0}</span></div>{memo?.comparable_properties.length ? <div className="data-grid">{memo.comparable_properties.map((item, index) => <div key={index}><strong>{String(item.address)}</strong><span>{money(item.sale_price as number | null)} · {String(item.square_feet ?? '—')} sq ft</span></div>)}</div> : <p className="muted">No verified comparable sales have been attached. Workbook sample comparables remain clearly marked as unverified.</p>}</article> }

function Documents({ propertyId, documents, refresh }: { propertyId: number; documents: Document[]; refresh: () => Promise<void> }) {
  const [type, setType] = useState('inspection')
  async function upload(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; const data = new FormData(); data.append('document_type', type); data.append('file', file); await fetch(`/api/properties/${propertyId}/documents`, { method: 'POST', body: data }); await refresh() }
  return <article className="panel"><div className="panel-title"><span>Due diligence documents</span><div className="upload-controls"><select value={type} onChange={(event) => setType(event.target.value)}><option value="inspection">Inspection</option><option value="survey">Survey</option><option value="permit">Permit</option><option value="photo">Photo</option><option value="floor_plan">Floor plan</option></select><label className="upload-button">Upload file<input type="file" onChange={(event) => void upload(event)} /></label></div></div><div className="document-list">{documents.map((document) => <a key={document.id} href={`/api/properties/${propertyId}/documents/${document.id}/download`}><span className="file-icon">▤</span><span><strong>{document.filename}</strong><small>{labelize(document.document_type)} · {Math.ceil(document.size_bytes / 1024)} KB</small></span><span>Download</span></a>)}{!documents.length && <p className="muted">Upload inspections, surveys, permits, photos, or floor plans.</p>}</div></article>
}

function NotesAndTasks({ propertyId, notes, tasks, refresh }: { propertyId: number; notes: Note[]; tasks: Task[]; refresh: () => Promise<void> }) {
  const [note, setNote] = useState(''); const [task, setTask] = useState('')
  async function add(path: 'notes' | 'tasks', body: Record<string, string>) { await fetch(`/api/properties/${propertyId}/${path}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); await refresh() }
  return <div className="two-column"><article className="panel"><div className="panel-title"><span>Internal notes</span></div><form className="inline-create" onSubmit={(event) => { event.preventDefault(); if (note) void add('notes', { body: note }).then(() => setNote('')) }}><input value={note} onChange={(event) => setNote(event.target.value)} placeholder="Add a diligence note…" /><button>Add</button></form><div className="note-list">{notes.map((item) => <div key={item.id}><p>{item.body}</p><small>{item.author ?? 'Bistate team'} · {new Date(item.created_at).toLocaleDateString()}</small></div>)}</div></article><article className="panel"><div className="panel-title"><span>Tasks</span></div><form className="inline-create" onSubmit={(event) => { event.preventDefault(); if (task) void add('tasks', { title: task }).then(() => setTask('')) }}><input value={task} onChange={(event) => setTask(event.target.value)} placeholder="Call broker, verify zoning…" /><button>Add</button></form>{tasks.map((item) => <TaskRow key={item.id} propertyId={propertyId} task={item} refresh={refresh} />)}</article></div>
}

function TaskRow({ propertyId, task, refresh }: { propertyId: number; task: Task; refresh: () => Promise<void> }) { return <label className={`task-row ${task.completed ? 'complete' : ''}`}><input type="checkbox" checked={task.completed} onChange={async (event) => { await fetch(`/api/properties/${propertyId}/tasks/${task.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ completed: event.target.checked }) }); await refresh() }} /><span><strong>{task.title}</strong><small>{task.assignee ?? 'Unassigned'}{task.due_date ? ` · Due ${task.due_date}` : ''}</small></span></label> }
function MemoList({ title, items, tone }: { title: string; items: string[]; tone: string }) { return <div className={`memo-list ${tone}`}><strong>{title}</strong>{items.length ? <ul>{items.map((item) => <li key={item}>{item}</li>)}</ul> : <p className="muted">None identified yet.</p>}</div> }
function Fact({ label, value }: { label: string; value: string }) { return <div><dt>{label}</dt><dd>{value}</dd></div> }
export function StatusDot({ status }: { status: string }) { return <span className={`status-dot status-${status.toLowerCase().replace(/ /g, '-')}`} title={status} /> }
export function EmptyState() { return <section className="empty-state"><div className="empty-icon">⌂</div><h1>Build your acquisition pipeline</h1><p>Paste a listing URL, property address, or MLS number above. Bistate will create the property, run enrichment, execute the workbook underwriting engine, and prepare an investment memo.</p></section> }
function labelize(value: string) { return value.replace(/_/g, ' ').replace(/\b\w/g, (letter: string) => letter.toUpperCase()) }
function money(value: number | null | undefined) { return value == null ? '—' : value.toLocaleString(undefined, { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }) }
function percent(value: number | null | undefined) { return value == null ? '—' : `${(value * 100).toFixed(1)}%` }
function score(value: number | null | undefined) { return value == null ? '—' : `${Math.round(value)}/100` }
function formatValue(value: unknown): string { if (typeof value === 'number') return Math.abs(value) < 1 ? percent(value) : value.toLocaleString(undefined, { maximumFractionDigits: 2 }); if (value === null) return '—'; if (Array.isArray(value)) return `${value.length} records`; if (typeof value === 'object') return 'View detailed output'; return String(value) }

