import { useEffect, useState } from 'react'

type Field = { key: string; label: string; kind?: string; value: unknown; source: string | null; display_status: string; confidence: number; last_updated: string | null; missing_reason: string | null }
type Insight = { severity?: string; title?: string; factual_basis: string; affected_use_cases: string[]; source_fields: string[]; recommended_action?: string }
type Completeness = { percentage_complete: number; auto_fields_total: number; auto_fields_covered: number; keyed_fields_total: number; keyed_fields_available: number; manual_diligence_remaining: number; verified_fields: number; unavailable_fields: number; providers_checked: number; stale_fields: number; manual_reviews_required: number; method: string }
type Intelligence = { sections: Array<{ name: string; fields: Field[] }>; red_flags: Insight[]; opportunities: Insight[]; completeness: Completeness }
const KIND_LABEL: Record<string, string> = { auto: 'Auto', keyed: 'Needs key', manual: 'Manual' }
type Health = { provider: string; source: string; configured: boolean; enabled: boolean; most_recent_success: string | null; most_recent_failure: string | null; latency_ms: number | null; cache_status: string; missing_credential_reason: string | null }

export function PropertyIntelligence({ propertyId, onRefreshed }: { propertyId: number; onRefreshed: () => Promise<void> }) {
  const [data, setData] = useState<Intelligence | null>(null); const [health, setHealth] = useState<Health[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  async function load() { const [intelligence, diagnostics] = await Promise.all([fetch(`/api/properties/${propertyId}/intelligence`), fetch('/api/properties/providers/health')]); if (!intelligence.ok) throw new Error('Property intelligence could not be loaded.'); setData(await intelligence.json() as Intelligence); if (diagnostics.ok) setHealth(await diagnostics.json() as Health[]) }
  useEffect(() => { setError(''); void load().catch((reason: Error) => setError(reason.message)) }, [propertyId]) // eslint-disable-line react-hooks/exhaustive-deps
  async function refresh() { setBusy(true); setError(''); try { const response = await fetch(`/api/properties/${propertyId}/enrich`, { method: 'POST' }); if (!response.ok) throw new Error('Refresh failed; stored facts remain available.'); await onRefreshed(); await load() } catch (reason) { setError((reason as Error).message) } finally { setBusy(false) } }
  if (error && !data) return <article className="panel"><p className="error-banner">{error}</p></article>
  if (!data) return <article className="panel"><p className="muted">Loading Property Intelligence…</p></article>
  const complete = data.completeness
  return <div className="intelligence-layout">
    <section className="panel intelligence-header"><div><div className="eyebrow">Automatic coverage from verified coordinates</div><h2>Data Completeness · {complete.percentage_complete}%</h2><p>{complete.method}</p></div><button onClick={() => void refresh()} disabled={busy}>{busy ? 'Refreshing…' : '↻ Refresh intelligence'}</button><div className="completeness-bar"><i style={{ width: `${complete.percentage_complete}%` }} /></div><div className="completeness-metrics"><span><b>{complete.auto_fields_covered}/{complete.auto_fields_total}</b> auto-retrieved</span><span><b>{complete.verified_fields}</b> verified facts</span><span><b>{complete.providers_checked}</b> providers returned data</span><span><b>{complete.keyed_fields_available}/{complete.keyed_fields_total}</b> unlock with an API key</span><span><b>{complete.manual_diligence_remaining}</b> manual diligence</span><span><b>{complete.stale_fields}</b> stale</span></div>{error && <p className="error-banner">{error}</p>}</section>
    {data.sections.map(section => <section className="intelligence-section" key={section.name}><h2>{section.name}</h2><div className="intelligence-fields">{section.fields.map(field => <article className="panel intelligence-field" key={field.key}><div className="panel-title"><span>{field.label}</span><span className={`fact-status status-${field.display_status.toLowerCase().replace(/ /g, '-')}`}>{field.display_status}</span></div><strong>{field.value == null ? '—' : format(field.value)}</strong><dl><div><dt>Type</dt><dd>{KIND_LABEL[field.kind ?? ''] ?? '—'}</dd></div><div><dt>Source</dt><dd>{field.source ?? 'No provider result'}</dd></div><div><dt>Confidence</dt><dd>{Math.round(field.confidence * 100)}%</dd></div></dl>{field.missing_reason && <p className="missing-reason">{field.missing_reason}</p>}</article>)}</div></section>)}
    <InsightSection title="Red flags" empty="No supported concerns were derived." items={data.red_flags} red /><InsightSection title="Opportunities" empty="No opportunities are supported by stored facts yet." items={data.opportunities} />
    <section className="panel diagnostics"><div className="panel-title"><span>Provider diagnostics</span><span>No secrets displayed</span></div><div className="diagnostic-list">{health.map(item => <div key={item.provider}><strong>{item.source}</strong><span>{item.configured ? 'Configured' : 'Unconfigured'} · {item.enabled ? 'Enabled' : 'Disabled'} · Cache: {item.cache_status}</span><small>Last success: {date(item.most_recent_success)} · Last failure: {date(item.most_recent_failure)} · Latency: {item.latency_ms == null ? '—' : `${item.latency_ms} ms`}</small>{item.missing_credential_reason && <small>{item.missing_credential_reason}</small>}</div>)}</div></section>
  </div>
}
function InsightSection({ title, items, empty, red = false }: { title: string; items: Insight[]; empty: string; red?: boolean }) { return <section className={`panel insight-section ${red ? 'red' : 'positive'}`}><div className="panel-title"><span>{title}</span><span>{items.length}</span></div>{items.length === 0 ? <p className="muted">{empty}</p> : <div className="insight-list">{items.map((item, index) => <article key={`${item.title ?? item.factual_basis}-${index}`}><b>{item.severity ?? item.title}</b><p>{item.factual_basis}</p><small>Affects: {item.affected_use_cases.join(', ')} · Sources: {item.source_fields.join(', ')}</small>{item.recommended_action && <em>Next: {item.recommended_action}</em>}</article>)}</div>}</section> }
function date(value: string | null) { return value ? new Date(value).toLocaleString() : 'Never' }
function format(value: unknown) { if (typeof value === 'number') return value.toLocaleString(); if (typeof value === 'object') return Object.entries(value as Record<string, unknown>).filter(([, item]) => item != null).map(([key, item]) => `${key.replace(/_/g, ' ')}: ${String(item)}`).join(' · ') || 'Available'; return String(value) }
