import { useState, type FormEvent } from 'react'

type Listing = { id: number; address: string; city: string; state: string; postal_code: string | null; county: string | null; asking_price: number | null; acreage: number | null; bedrooms: number | null; bathrooms: number | null; property_type: string | null; photo_url: string | null; listing_source: string; listing_date: string | null; is_watchlisted: boolean }
type Filters = { county: string; town: string; postal_code: string; min_price: string; max_price: string; min_acreage: string; bedrooms: string; property_type: string }
const initial: Filters = { county: '', town: '', postal_code: '', min_price: '', max_price: '', min_acreage: '', bedrooms: '', property_type: '' }

export default function SearchPage({ onPipeline }: { onPipeline: () => void }) {
  const [filters, setFilters] = useState(initial); const [results, setResults] = useState<Listing[]>([]); const [message, setMessage] = useState('Choose filters and search Zillow, Realtor, Redfin, and LandWatch.'); const [busy, setBusy] = useState(false)
  const set = (key: keyof Filters, value: string) => setFilters((current) => ({ ...current, [key]: value }))
  async function search(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(''); const payload = Object.fromEntries(Object.entries(filters).filter(([, value]) => value !== '').map(([key, value]) => [key, ['min_price', 'max_price', 'min_acreage', 'bedrooms'].includes(key) ? Number(value) : value])); try { const response = await fetch('/api/discovery/search', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); if (!response.ok) throw new Error('Search could not be completed.'); const data = await response.json() as Listing[]; setResults(data); setMessage(data.length ? '' : 'No listings match these filters.'); } catch (error) { setMessage((error as Error).message) } finally { setBusy(false) } }
  async function watch(listing: Listing) { const response = await fetch(`/api/discovery/listings/${listing.id}/watchlist`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ is_watchlisted: !listing.is_watchlisted }) }); if (response.ok) setResults((items) => items.map((item) => item.id === listing.id ? { ...item, is_watchlisted: !item.is_watchlisted } : item)) }
  async function analyze(listing: Listing) { setBusy(true); const response = await fetch(`/api/discovery/listings/${listing.id}/analyze`, { method: 'POST' }); setBusy(false); if (response.ok) onPipeline(); else setMessage('This listing is already in the underwriting pipeline.') }
  return <main className="discovery-page"><header className="discovery-header"><div><span className="eyebrow">Listing Discovery</span><h1>Find your next opportunity.</h1><p>Search candidates before they enter underwriting.</p></div><button className="secondary-button" onClick={onPipeline}>Open pipeline</button></header><form className="filter-panel" onSubmit={search}>{([['county', 'County'], ['town', 'Town'], ['postal_code', 'ZIP code'], ['min_price', 'Min price'], ['max_price', 'Max price'], ['min_acreage', 'Min acreage'], ['bedrooms', 'Bedrooms']] as Array<[keyof Filters, string]>).map(([key, label]) => <label key={key}>{label}<input aria-label={label} type={key.includes('price') || key === 'min_acreage' || key === 'bedrooms' ? 'number' : 'text'} value={filters[key]} onChange={(e) => set(key, e.target.value)} /></label>)}<label>Property type<select aria-label="Property type" value={filters.property_type} onChange={(e) => set('property_type', e.target.value)}><option value="">Any type</option><option>Single Family</option><option>Land</option><option>Condo</option></select></label><button>{busy ? 'Searching…' : 'Search listings'}</button></form>{message && <p className="discovery-message">{message}</p>}<section className="listing-grid" aria-live="polite">{results.map((listing) => <article className="listing-card" key={listing.id}><img src={listing.photo_url ?? ''} alt={`Property at ${listing.address}`} /><div className="listing-body"><div className="listing-meta"><span>{listing.listing_source}</span><time>{listing.listing_date ? new Date(listing.listing_date).toLocaleDateString() : 'Date unavailable'}</time></div><h2>{listing.address}</h2><p>{listing.city}, {listing.state} {listing.postal_code} · {listing.county} County</p><strong>${listing.asking_price?.toLocaleString() ?? '—'}</strong><div className="listing-facts">{listing.bedrooms ?? '—'} bd · {listing.bathrooms ?? '—'} ba · {listing.acreage ?? '—'} acres · {listing.property_type}</div><div className="listing-actions"><button className="secondary-button" onClick={() => void watch(listing)}>{listing.is_watchlisted ? 'Saved to Watchlist' : 'Save to Watchlist'}</button><button onClick={() => void analyze(listing)} disabled={busy}>Analyze</button></div></div></article>)}</section></main>
}
